const USER_ACTION_TYPES = {
  CREATE_NEW_USER: "CREATE_NEW_USER",
  CREATE_NEW_USER_SUCCESS: "CREATE_NEW_USER_SUCCESS",
  CREATE_NEW_USER_FAIL: "CREATE_NEW_USER_FAIL"
};

export default USER_ACTION_TYPES;
